services:
  - type: web
    name: chunking-methods-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:$PORT app:create_app"
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false 